export type LocalisationKeys =
  // chain
  | 'chain.all.label'
  | 'chain.more.label'
  // wallet
  | 'wallet.recipient.placeholder'
  | 'wallet.recipient.info.selectToken'
  | 'wallet.recipient.error.noAddress'
  | 'wallet.recipient.error.tokenNotSelected'
  | 'wallet.recipient.error.invalidAddress'
  | 'wallet.recipient.error.sendAddressNotFound'
  | 'wallet.recipient.error.sendAddressInvalid'
  | 'wallet.recipient.warn.compatibleNetwork'
  | 'wallet.recipient.message.networkVerified'
  | 'wallet.recipient.message.receiveFunds'
  | 'wallet.connected.error.notSupportedChain'
  // transfer
  | 'transfer.success.swap.title'
  | 'transfer.success.withdrawal.title'
  | 'transfer.success.deposit.title'
  | 'transfer.success.details.label'
  | 'transfer.success.details.hash'
  | 'transfer.success.details.rate'
  | 'transfer.success.details.intent'
  | 'transfer.success.details.recipient'
  | 'transfer.success.action.viewOnExplorer'
  | 'transfer.success.action.backToSwap'
  // quote
  | 'quote.result.maxSlippage.label'
  | 'quote.result.processingTime.label'
  // tokens
  | 'tokens.input.max.label'
  | 'tokens.input.half.label'
  | 'tokens.input.externalBalance.label'
  | 'tokens.input.externalBalanceOnly.label'
  | 'tokens.list.noBalanceOnApp.label'
  | 'tokens.list.noBalanceOnApp.subLabel'
  | 'tokens.list.searchEmpty.label'
  | 'tokens.list.searchEmpty.subLabel'
  | 'tokens.list.searchReset.label'
  // deposit
  | 'deposit.external.error.noStatus'
  | 'deposit.external.error.incomplete'
  | 'deposit.external.error.failed'
  | 'deposit.external.loading.waiting'
  | 'deposit.external.loading.fetching'
  | 'deposit.method.switcher.label'
  | 'deposit.summary.youWillDeposit.label'
  | 'deposit.summary.title'
  // submit - errors
  | 'submit.error.connectWallet'
  | 'submit.error.invalidTransferData.label'
  | 'submit.error.transferFailed.label'
  | 'submit.error.insufficientBalance'
  | 'submit.error.invalidAddress'
  | 'submit.error.sendAddressNotFound'
  | 'submit.error.sendAddressInvalid'
  | 'submit.error.amountTooLow.label'
  | 'submit.error.amountTooLow.message'
  | 'submit.error.quoteFailed.label'
  | 'submit.error.quoteFailed.message'
  | 'submit.error.transfer.noFees'
  | 'submit.error.transfer.failed'
  | 'submit.error.externalTransferFailed.label'
  | 'submit.error.externalTransferFailed.incompleteMessage'
  | 'submit.error.externalTransferFailed.refundedMessage'
  // send address
  | 'sendAddress.label'
  | 'sendAddress.button.magic.label'
  // submit - active (swap)
  | 'submit.active.swap'
  | 'submit.active.intentsSwap'
  // submit - active (withdraw)
  | 'submit.active.withdraw'
  // submit - active (deposit)
  | 'submit.active.deposit'
  // submit - disabled
  | 'submit.disabled.temporary.label'
  | 'submit.disabled.temporary.message'
  | 'submit.disabled.selectTokenToReceive'
  | 'submit.disabled.enterRecipientAddress'
  | 'submit.disabled.enterAmount'
  // submit - pending
  | 'submit.pending.quote.finalizing'
  | 'submit.pending.quote.refreshing'
  | 'submit.pending.transfer.confirmInWallet'
  | 'submit.pending.transfer.finalizing'
  | 'submit.pending.externalDeposit.waiting'
  | 'submit.pending.externalDeposit.processing'
  | 'submit.pending.switchingChain'
  | 'submit.pending.validating'
  // wallet compatibility
  | 'walletCompatibility.modal.title.initial'
  | 'walletCompatibility.modal.title.error'
  | 'walletCompatibility.modal.description.initial'
  | 'walletCompatibility.modal.description.error'
  | 'walletCompatibility.modal.feature.secureTransactions'
  | 'walletCompatibility.modal.feature.fullAccess'
  | 'walletCompatibility.modal.feature.fundProtection'
  | 'walletCompatibility.modal.button.verified'
  | 'walletCompatibility.modal.button.signing'
  | 'walletCompatibility.modal.button.verify'
  | 'walletCompatibility.modal.button.closeTimer'
  | 'walletCompatibility.modal.button.tryAgain'
  | 'walletCompatibility.modal.button.tryAgainDesc'
  | 'walletCompatibility.modal.button.signOut'
  // token input
  | 'tokenInput.heading.source.withdraw'
  | 'tokenInput.heading.target.withdraw'
  | 'tokenInput.heading.source.deposit'
  | 'tokenInput.heading.source.swap'
  | 'tokenInput.heading.target.swap';

export type LocalisationDict = Partial<Record<LocalisationKeys, string>>;
